# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7f7e265f80daaa904d03612ac0ac68e3d5cd11201fab3d9c786dac4f2f25da69c5cc92fbe35226fe9f42cf8246a3a0cb9c727c01ad37c194e06f7139d9988ac

test:
  secret_key_base: 15945b4c2de5b0f48f78022f1d2ebba96997ea6a5a73ef86a47b53056e3890c2194bc43de865fa31a572e6e0c5c1242376e50344b958ec76944536afca0cb38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
